# Generated by Django 5.0.7 on 2024-09-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='iframe_code',
            field=models.TextField(blank=True, null=True, verbose_name='Código del Iframe del Video'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default=1, upload_to='imagenes/articulos/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
