# Generated by Django 5.0.7 on 2024-09-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_articulo_iframe_code_articulo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='slug',
        ),
    ]
