# Generated by Django 5.0.7 on 2024-09-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_remove_articulo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='estadoArt',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
