# Generated by Django 5.0.7 on 2024-10-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_seccionweb1'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionweb1',
            name='tituloDescripcion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
