# Generated by Django 5.0.7 on 2024-10-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_seccionweb1_titulodescripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionweb1',
            name='tituloDescripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
