# Generated by Django 5.0.7 on 2024-10-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_alter_imagen_imagen'),
        ('web', '0008_alter_seccionweb1_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionWeb2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='pro.categoria')),
            ],
        ),
    ]
