# Generated by Django 5.0.7 on 2024-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_seccionweb2'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionweb2',
            name='tituloDescripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
