# Generated by Django 5.0.7 on 2024-10-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_alter_imagen_imagen'),
        ('web', '0010_seccionweb2_titulodescripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccionweb2',
            name='categorias',
        ),
        migrations.AddField(
            model_name='seccionweb2',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias', to='pro.categoria'),
        ),
    ]
