# Generated by Django 5.0.7 on 2024-10-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_alter_imagen_imagen'),
        ('web', '0012_remove_seccionweb2_categorias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionWeb3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('tituloContador1', models.CharField(max_length=255)),
                ('contador1', models.IntegerField()),
                ('tituloContador2', models.CharField(max_length=255)),
                ('contador2', models.IntegerField()),
                ('tituloContador3', models.CharField(max_length=255)),
                ('contador3', models.IntegerField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='seccion3/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='seccion3/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='seccion3/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='seccion3/')),
            ],
        ),
        migrations.RemoveField(
            model_name='seccionweb2',
            name='contador1',
        ),
        migrations.RemoveField(
            model_name='seccionweb2',
            name='contador2',
        ),
        migrations.RemoveField(
            model_name='seccionweb2',
            name='contador3',
        ),
        migrations.RemoveField(
            model_name='seccionweb2',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='seccionweb2',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='seccionweb2',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='seccionweb2',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='seccionweb2',
            name='tituloContador1',
        ),
        migrations.RemoveField(
            model_name='seccionweb2',
            name='tituloContador2',
        ),
        migrations.RemoveField(
            model_name='seccionweb2',
            name='tituloContador3',
        ),
        migrations.AddField(
            model_name='seccionweb2',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias', to='pro.categoria'),
        ),
        migrations.AddField(
            model_name='seccionweb2',
            name='tituloDescripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
