# Generated by Django 5.0.7 on 2024-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_seccionweb3_contadorimg1_seccionweb3_contadorimg2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionweb3',
            name='descripcionImg1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccionweb3',
            name='descripcionImg2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccionweb3',
            name='descripcionImg3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccionweb3',
            name='descripcionImg4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seccionweb3',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='bannerSeccion3/'),
        ),
        migrations.AlterField(
            model_name='seccionweb3',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='bannerSeccion3/'),
        ),
        migrations.AlterField(
            model_name='seccionweb3',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='bannerSeccion3/'),
        ),
        migrations.AlterField(
            model_name='seccionweb3',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='bannerSeccion3/'),
        ),
    ]
