# Generated by Django 5.0.7 on 2024-10-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_seccionweb3_descripcionimg1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionWeb4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
    ]
