# Generated by Django 5.0.7 on 2024-10-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_rename_boton_seccionweb5_boton1_seccionweb5_boton2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionWeb6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcionImg4', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bannerSeccion5/')),
                ('boton', models.CharField(max_length=255)),
            ],
        ),
    ]
