# Generated by Django 5.0.7 on 2024-10-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_testimonio_seccionweb7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionweb7',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='seccion7/'),
        ),
    ]
