# Generated by Django 5.0.7 on 2024-10-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_alter_seccionweb7_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccionweb7',
            name='boton',
        ),
    ]
