# Generated by Django 5.0.7 on 2024-10-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_remove_seccionweb7_boton'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionWeb8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('boton', models.CharField(max_length=255)),
                ('contadorImg1', models.IntegerField()),
                ('tituloImg1', models.CharField(max_length=255)),
                ('descripcionImg1', models.CharField(max_length=255)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='bannerSeccion8/')),
                ('contadorImg2', models.IntegerField()),
                ('tituloImg2', models.CharField(max_length=255)),
                ('descripcionImg2', models.CharField(max_length=255)),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='bannerSeccion8/')),
                ('contadorImg3', models.IntegerField()),
                ('tituloImg3', models.CharField(max_length=255)),
                ('descripcionImg3', models.CharField(max_length=255)),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='bannerSeccion8/')),
                ('contadorImg4', models.IntegerField()),
                ('tituloImg4', models.CharField(max_length=255)),
                ('descripcionImg4', models.CharField(max_length=255)),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='bannerSeccion8/')),
            ],
        ),
    ]
