# Generated by Django 5.0.7 on 2024-10-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_seccionweb8'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionweb8',
            name='boton1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccionweb8',
            name='boton2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccionweb8',
            name='boton3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccionweb8',
            name='boton4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
