# Generated by Django 5.0.7 on 2024-10-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_seccionweb8_boton1_seccionweb8_boton2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionweb8',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='bannerSeccion8/'),
        ),
    ]
