# Generated by Django 5.0.7 on 2024-10-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_remove_seccionweb9_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenesIg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionWeb10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('imgs', models.ManyToManyField(related_name='testimonios', to='web.imagenesig')),
            ],
        ),
    ]
