# Generated by Django 5.0.7 on 2024-10-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_imagenesig_seccionweb10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccionweb10',
            name='imgs',
        ),
        migrations.AddField(
            model_name='seccionweb10',
            name='imgIg',
            field=models.ManyToManyField(related_name='imagenesIg', to='web.imagenesig'),
        ),
    ]
