# Generated by Django 5.0.7 on 2024-10-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_remove_seccionweb10_imgs_seccionweb10_imgig'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='breadcrumb',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banners',
            name='texto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
