# Generated by Django 5.0.7 on 2024-08-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upload/images/empresa')),
                ('web', models.URLField(blank=True, null=True)),
                ('terminos', models.TextField(blank=True, max_length=512, null=True)),
                ('nit', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
