# Generated by Django 5.0.7 on 2024-08-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_ven',
        ),
    ]
