# Generated by Django 5.0.7 on 2024-09-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0002_empresa_uc_albumgallery_imagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='iframe_code',
            field=models.TextField(blank=True, null=True, verbose_name='Código del Iframe del Video'),
        ),
    ]
