# Generated by Django 5.0.7 on 2024-09-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0003_albumgallery_imagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumgallery',
            name='imagen',
            field=models.ImageField(default=1, upload_to='imagenes/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
