# Generated by Django 5.0.7 on 2024-08-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensiones', models.CharField(blank=True, help_text='Dimensiones del producto', max_length=100, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=6, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=200, null=True)),
                ('tamano_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Tamaño máximo en cm', max_digits=5, null=True)),
                ('temperatura_recomendada', models.CharField(blank=True, help_text='Rango de temperatura en °C', max_length=50, null=True)),
                ('ph_recomendado', models.CharField(blank=True, help_text='Rango de pH', max_length=50, null=True)),
                ('dieta', models.CharField(blank=True, max_length=200, null=True)),
                ('cuidados_especiales', models.TextField(blank=True, null=True)),
                ('tipo_equipo', models.CharField(blank=True, help_text='Tipo de equipo (ej. filtro, bomba)', max_length=100, null=True)),
                ('capacidad', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad del equipo (ej. litros por hora)', max_digits=10, null=True)),
                ('uso_recomendado', models.TextField(blank=True, help_text='Descripción de uso recomendado', null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('disponible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
