# Generated by Django 5.0.7 on 2024-08-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_categoria_creado_por_imagen_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cuidados_especiales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='dieta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_cientifico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ph_recomendado',
            field=models.CharField(blank=True, help_text='Rango de pH', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamano_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tamaño máximo en cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='temperatura_recomendada',
            field=models.CharField(blank=True, help_text='Rango de temperatura en °C', max_length=50, null=True),
        ),
    ]
