# Generated by Django 5.0.7 on 2024-08-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_remove_producto_imagenes_adicionales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
