# Generated by Django 5.0.7 on 2024-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_producto_cuidados_especiales_producto_dieta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='capacidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad del equipo (ej. litros por hora)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='dimensiones',
            field=models.CharField(blank=True, help_text='Dimensiones del producto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_equipo',
            field=models.CharField(blank=True, help_text='Tipo de equipo (ej. filtro, bomba)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='uso_recomendado',
            field=models.TextField(blank=True, help_text='Descripción de uso recomendado', null=True),
        ),
    ]
