# Generated by Django 5.0.7 on 2024-08-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_rename_titulo_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cuidados_especiales',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='dieta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='material',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_cientifico',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ph_recomendado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tamano_maximo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='temperatura_recomendada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_equipo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='uso_recomendado',
        ),
    ]
