# Generated by Django 5.0.7 on 2024-09-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_remove_producto_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='productos/imagenes/'),
        ),
    ]
